apiVersion: 1

datasources:
  - name: Postgres
    uid: postgres
    type: postgres
    access: proxy
    url: ${PG_HOST}:${PG_PORT}
    user: ${PG_USER_RO}
    database: ${PG_DB}
    secureJsonData:
      password: ${PG_PASS_RO}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    editable: false
