services:
  lavinmq:
    image: cloudamqp/lavinmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - lavinmq_data:/var/lib/lavinmq

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: queroplantao_messaging
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  lavinmq_data:
  redis_data:
  postgres_data:
