export const SUSPICIOUS_DDI_PREFIXES = ["27", "57", "62"] as const;

export const SUSPICIOUS_NAMES = [
  "Med Open",
  "MedOpen",
  "Med Max",
  "MedMax",
  "Med Flix",
  "MedFlix",
  "Med Curso",
  "Esteto",
  "Kot",
];

// Unificado: texto OU caption (script n8n tinha 2 listas idênticas por limitação da plataforma)
export const SUSPICIOUS_CONTENT = [
  "Drive 2025",
  "Drive 2026",
  "Drive 2025/26",
  "Ⓜ️Drive",
  "Medcurso",
  "Medgrupo",
  "Medcel",
  "Medcof",
  "MedFoco",
  "MedAnki",
  "Medway",
  "MedWay",
  "Hardwork Medicina",
  "EstratégiaMed",
  "Estratégia Med",
  "MEDsimple",
  "MedNeif",
  "MEDREVIEW",
  "CasalMed",
  "Med Eletro",
  "MedEletro",
  "Medeletro",
  "PS Zerado",
  "Eu Médico Residente",
  "Ortoacademy",
  "ORTOP-REVIEW",
  "Clinicof",
  "Fluimed",
  "Oftalmocurso",
  "Oftreview",
  "Opuscurso",
  "Anestreview",
  "SOS Neurocirurgião",
  "qrad.com.br",
  "hotmart.com",
  "hotmart.host",
  "Pacote Medgrupo",
  "Pacote Medcel",
  "Pacote Medcof",
  "Pacote Medway",
  "Pacote Hardwork",
  "Pacote Estratégia",
  "140 cursos",
  "ARTIGO COMPLETO",
  "Flashcards",
  "Flashcards ANKI",
  "Banco de Questões",
  "Banco do Estratégia",
  "Banco do Medcurso",
  "REVALIDA 2025",
  "Intensivão R1",
  "Intensivo R1",
  "Sprint Estratégia",
  "SPRINTS Estratégia",
  "Mentoria Pré-Edital Residência",
  "Pré-Edital Residência",
  "Dominando a multimídia",
  "Dominando Multimídia",
  "Raio X da Banca",
  "HIIT Cirurgia",
  "POCUS - Point of Care",
  "Endocrinopapers",
  "Nefropapers",
  "Neuropost",
  "Dermatopapers",
  "Cardiopapers",
  "hub2med.com",
  "vagas.rcs.med.br",
  "hub2med",
  "trabalhemed",
  "TRABALHEMED",
  "https://tk7.games",
  "https://lv7.io",
  "https://58s.game",
  "https://br7.fun",
  "https://to7.game",
  "https://bmw7.game",
  "https://njr7.org",
  "https://pp7.wtf",
  "plataforma de slots",
  "butterfly iq+",
  "gradualmedic.com.br",
  "lumify linear",
  "ULTRASSOM LINEAR PHILLIPS",
  "ULTRASSOM PORTÁTIL",
  "Littmann Classic III original (3M)",
  "𝐜𝐚ç𝐚-𝐧í𝐪𝐮𝐞𝐢𝐬",
  "𝐀 𝐩𝐥𝐚𝐭𝐚𝐟𝐨𝐫𝐦𝐚 𝐝𝐞 𝐜𝐚ç𝐚-𝐧í𝐪𝐮𝐞𝐢𝐬",
  "Entre agora no grupo do Telegram para começar a ganhar grandes lucros diariamente na mineração de criptomoedas.",
];
